name: NovaCare QA Automation

on:
  push:
  workflow_dispatch:

jobs:
  browserstack-run:
    name: Run Cypress tests on BrowserStack
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "18"

      - name: Confirm Node.js and npm versions
        run: |
          echo "Node.js version:"
          node -v
          echo "npm version:"
          npm -v

      - name: Install dependencies
        run: |
          echo "Installing project dependencies..."
          npm install

      - name: Run Cypress tests on BrowserStack
        run: |
          echo "Starting automated tests on BrowserStack..."
          echo "BrowserStack Username: $BROWSERSTACK_USERNAME"
          echo "BrowserStack Project: $BROWSERSTACK_PROJECT_NAME"
          echo "Build Name: $BROWSERSTACK_BUILD_NAME"
          npx browserstack-cypress run --spec 'cypress/e2e/functional/**/*.cy.js' 2>&1 | tee browserstack-output.log
          exit_code=${PIPESTATUS[0]}
          echo "BrowserStack exit code: $exit_code"
          exit $exit_code
        env:
          BROWSERSTACK_USERNAME: ${{ secrets.BROWSERSTACK_USERNAME }}
          BROWSERSTACK_ACCESS_KEY: ${{ secrets.BROWSERSTACK_ACCESS_KEY }}
          BROWSERSTACK_PROJECT_NAME: "NovoCare-QA-Automation"
          BROWSERSTACK_BUILD_NAME: "${{ github.workflow }} - ${{ github.run_number }}"

      - name: Upload BrowserStack logs
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: browserstack-logs
          path: browserstack-output.log

      - name: Upload config files
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: config-files
          path: |
            cypress.config.js
            browserstack.json

  cloud-tests:
      name: Run Cypress tests on Cypress Cloud
      runs-on: self-hosted
  
      steps:
        - name: Checkout repo
          uses: actions/checkout@v4
  
        - name: Setup Node.js
          uses: actions/setup-node@v4
          with:
            node-version: "18"
  
        - name: Install dependencies
          run: |
            echo "Installing project dependencies..."
            npm install
  
        - name: Run Cypress tests with Cloud recording
          env:
            CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
          run: |
            echo "Running Cypress tests and uploading to Cypress Cloud..."
            echo "Command: npx cypress run --record --key \$CYPRESS_RECORD_KEY --spec \"cypress/e2e/functional/**/*.cy.js\""
            npx cypress run --record --key $CYPRESS_RECORD_KEY --spec "cypress/e2e/functional/**/*.cy.js" 2>&1 | tee cypress-cloud-output.log
            exit_code=${PIPESTATUS[0]}
            echo "Cypress Cloud exit code: $exit_code"
            exit $exit_code
  
        - name: Upload Cypress Cloud log
          if: always()
          uses: actions/upload-artifact@v4
          with:
            name: cypress-cloud-log
            path: cypress-cloud-output.log
